services:
  db_vinogradiya:
    build: 
      context: .
      dockerfile: docker/database/Dockerfile
    container_name: db_vinogradiya
    volumes:
      - ./pgdataforvinogradiya:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vinogradiya
      POSTGRES_USER: andreyJdev
      POSTGRES_PASSWORD: htahb;thfnjh
    restart: unless-stopped
    ports:
      - "5434:5432"
    networks:
      - vinogradiya-website

  website:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    restart: unless-stopped
    depends_on:
      - db_vinogradiya
    ports:
      - "45532:8080"
    volumes:
      - static-resources:/opt/src/static-resources
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_vinogradiya:5432/vinogradiya
      - SPRING_DATASOURCE_USERNAME=andreyJdev
      - SPRING_DATASOURCE_PASSWORD=htahb;thfnjh
      - SPRING_DATASOURCE_STATIC=/opt/src/static-resources
    networks:
      - vinogradiya-website

networks:
  vinogradiya-website:
    driver: bridge

volumes:
  pgdataforvinogradiya:
  static-resources:
    driver: local
    driver_opts:
      type: none
      device: ./src/main/resources/static
      o: bind